#!/bin/sh
# 2003-2010 Etersoft www.etersoft.ru
# Public domain
# 20.06.04, 15.01.05, 28.02.05, 07.03.05, 07.09.05, 09.04.06
# 
# Config file for etersoft-build-utils
# You can copy this file as ~/.config/eterbuild for per user settings
# and uncomment any setting line

# Путь к каталогу сборки hasher:
#HASHERBASEDIR=~/hasher
# Additional arguments for hasher
#HASHER_ARG=""

# Удалённый сборочный сервер в нотации ssh (для сборки при rpmbsh -r)
#BUILDSERVER="builder64"

# FIXME: используется?
# TODO: Каталог на сборочном сервере с собранными в hasher пакетами
#BUILDSERVERPATH=$HASHERDIR/repo/i586/RPMS.hasher

# FIXME: используется?
# Кому отправлять отчёт, на какой адрес
#OWNERMAIL="Vitaly Lipatov <lav@altlinux.ru>"

# Повышенная говорливость
#DEBUG="-v"

# Каталог сборки, указываемый в переменной %_tmppath .rpmmacros
#BUILDROOT=

# Default arch for 32-bit packages (x86_64 will used for 64-bit packages)
#BUILDARCH=i586

# Default ~/RPM path
#RPMDIR=$HOME/RPM

# Path to apt config
#APTCONFBASE=/etc/eterbuild/apt/apt.conf

# Адрес ftp-сервера компании
#COMPANYFTP=etersoft.ru

# Базовый каталог расположения ftp-сервера (поддерживаются локальные и ssh-пути)
#TARGETFTPBASE=ftp.eter:/var/ftp

# Каталог для записи протоколов сборки
#LOGDIR=$RPMDIR/log

# Ключ, используемый при отправке
#SSH_KEYFILE=~/.ssh/id_dsa

# See sisyphus_check --help for other options
#HASHER_NOCHECK=nvr,gpg,packager,buildtime

# Rename source tarball to tar.bz2 in rpmcs command
#RENAME_SOURCE_TARBALL=0

# Always pack src.rpm by legacy gzip compression
#USE_LEGACY_COMPRESSION=0

# TODO: autodetect from sources.list
# Path to local Sisyphus repo (where i586/RPMS.classic) for rpmunmets build
#SISYPHUSPATH=/var/ftp/pub/ALTLinux/Sisyphus/

# enable ccache using
# CCACHE_ENABLE=yes

# set dir for ccache cache
# export CCACHE_DIR=$OURTMPDIR/ccache

# username on $GIRARHOST host
# GIRAR_USER=lav

# default girar ssh alias
# autodetect gitery, git.alt if not set here
# GIRARHOST=git.alt

# Skip error if there are unpackaged files in the build
#NOSTRICT_UNPACKAGED=1

# Path to default dir with git repos (used in rpmgp -m).
#GITREPODIR=.

# Build for Sisyphus by default
# MENV=SS

# distcc support in jmake
# https://wiki.office.etersoft.ru/devel/distrubutedcompilation
# i586 only systems
# DISTCC_32_HOSTS="euclid atlant"
# DISTCC_32_THREADS=12

# x86_64 (gcc -m32 supports too)
# DISTCC_64_HOSTS="builder64"
# DISTCC_64_THREADS=12
