#!/bin/bash
# 2003-2008 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

is_alt()
{
	test -f /etc/altlinux-release
	return $?
}

# Internal
set_target_type()
{
	if echo $1 | grep "^M[0-9][0-9]$" >/dev/null ; then
		MENV=$1
		return 0
	fi
	case "$1" in
		("DD" | "SS" | "EE")
			MENV="$1"
			return 0;
			;;
	esac
	return 1;
}

set_incoming()
{
	INCOMING="Sisyphus"
	test -z "$1" && return
	case "$1" in
		("DD")
			INCOMING="Daedalus"
			;;
		("SS")
			INCOMING="Sisyphus"
			;;
		*)
			if [ -n "$UPDATES" ] ; then
				INCOMING="updates/`get_altdistr_version $1`"
			else
				INCOMING="backports/`get_altdistr_version $1`"
			fi
			;;
	esac
}

set_binaryrepo()
{
	BINARYREPO="sisyphus"
	test -z "$1" && return
	case "$1" in
		("DD")
			BINARYREPO="daedalus"
			;;
		("SS")
			BINARYREPO="sisyphus"
			;;
		*)
			# TODO
			if [ -n "$UPDATES" ] ; then
				BINARYREPO="`get_altdistr_version $1`"
			else
				BINARYREPO="`get_altdistr_version $1`"
			fi
			;;
	esac
}

# M50 -> 5.0
get_altdistr_version()
{
	echo "$1" | sed -e "s|M\([0-9]\)\([0-9]\)|\1\.\2|g" | sed -e "s|SS|Sisyphus|g" | sed -e "s|DD|Daedalus|g"
}

# 5.0 -> M50
get_altdistr_mod()
{
	echo "$1" | sed -e "s|\([0-9]\)\.\([0-9]\)|M\1\2|g" | sed -e "s|Sisyphus|SS|g"
}

# TODO: include in sisyphus_check
# Проверяем, соответствует ли релиз пакетов указанному в MENV
function pkg_release_check()
{
	local STREL=alt
	[ -z "$KORINFTARGETRELEASE" ] || STREL=$KORINFTARGETRELEASE

	if [ "$MENV" = "SS" ] || [ "$MENV" = "DD" ] ; then
		for i in $@ ; do
			if [ -z "${i/*$STREL[0-9].M[0-9][0-9]*/}" ] ; then
				# Значит не тот релиз
				fatal "Incorrect release in $i package: was prepared for Sisyphus"
			fi
		done
		return
	fi
	for i in $@ ; do
		if [ -n "${i/*$STREL[0-9].$MENV*/}" ] ; then
			# Значит не тот релиз
			fatal "Incorrect release in $i package: was prepared for $MENV"
		fi
	done
}
