#!/bin/bash
# 2008, 2011 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain


get_gear_rules()
{
	local SPECNAME="$1"
	# FIXME: move get rules file to separate function
	local BASESPECNAME=$(basename "$SPECNAME")
	local ALTGEARRULESFILE=.gear/rules-${BASESPECNAME/.spec/}
	local ALTGEARRULES=$(git rev-parse --git-dir)/../$ALTGEARRULESFILE
	local GEARRULES=
	if [ -r "$ALTGEARRULES" ] ; then
		#echo "Build with alternate rules $ALTGEARRULESFILE"
		GEARRULES="--rules=$ALTGEARRULESFILE"
	fi
	echo "$GEARRULES"
}

# Universal rpmbuild function
# 1st: spec name(s) (only one if git, we will skip it)
# other parameters
uni_rpmbuild()
{
	local RET=0

	local FIVEPARAM="--define=_unpackaged_files_terminate_build 0"

	local COMMIT=""
	local COMMANDAFTER=""
	if [ "$1" = "--commit" ] ; then
		shift
		COMMIT="--commit"
		COMMANDAFTER="git reset"
	fi

	local SPECNAME="$1"
	local SPECDIR=`dirname $SPECNAME`
	local GEAR=gear

	local THRPARAM="--quiet"
	[ -n "$USE_VENDOR" ] && THRPARAM="--define=_vendor $USE_VENDOR"

	local TWOPARAM="--quiet"
	[ -n "$RPMTOPDIR" ] && TWOPARAM="--define=_topdir $RPMTOPDIR"

	local FOURPARAM="--quiet"
	if [ -n "$CCACHE_ENABLE" ] && [ -n "$CCACHE_DIR" ] ; then
		FOURPARAM="--define=__ccache_dir $CCACHE_DIR"
	fi


	if is_gear $SPECDIR ; then
		[ -f "$SPECNAME" ] || fatal "run uni_rpmbuild with spec as 2nd parameter"
		shift # skip spec name

		# FIXME: use spec name as project name
		GEARRULES=$(get_gear_rules "$SPECNAME")

		# build package without MENV checking
		if true || [ "$MENV" = "SS" ] ; then
			showcmd $GEAR $COMMIT $GEARRULES --rpmbuild -- $RPMBUILD "$TWOPARAM" "$THRPARAM" "$FOURPARAM" "$FIVEPARAM" "$SIXPARAM" $@
			$NICE $GEAR $COMMIT $GEARRULES --rpmbuild -- $RPMBUILD "$TWOPARAM" "$THRPARAM" "$FOURPARAM" "$FIVEPARAM" "$SIXPARAM" $@ || RET=$?
			[ -z "$COMMANDAFTER" ] || docmd $COMMANDAFTER
		else
			fatal "Build backported src.rpm from git is unsupported now"
			# build src.rpm via hasher (on ALT)
#			$NICE gear-hsh --build-args="-bs" --rpmbuild -- $COMMAND "$ONEPARAM" $@
			#docmd $NICE $GEAR --hasher -- myhsh --build-prog=$ETERBUILDDIR/functions/rebuild $@ || RET=$?
		fi
	else
		mkdir -p $RPMTOPDIR/BUILD $RPMTOPDIR/SRPMS
		showcmd $RPMBUILD "$TWOPARAM" "$THRPARAM" "$FOURPARAM" "$FIVEPARAM" "$SIXPARAM" $@
		$NICE $RPMBUILD "$TWOPARAM" "$THRPARAM" "$FOURPARAM" "$FIVEPARAM" "$SIXPARAM" $@ || RET=$?
	fi

	return $RET
}


uni_buildreq()
{
	local RET=0
	local BUILDREQPARAM="$1"
	shift
	local SPECNAME=$(realpath "$1")
	shift
	local SPECDIR=`dirname $SPECNAME`
	local GEARBUILDREQ=gear-buildreq

	if is_gear $SPECDIR ; then
		showcmd $GEARBUILDREQ $BUILDREQPARAM --commit -- "$SPECNAME" $@
		$NICE $GEARBUILDREQ $BUILDREQPARAM --commit -- "$SPECNAME" $@ || RET=$?
	else
		showcmd buildreq $BUILDREQPARAM "$SPECNAME" $@
		$NICE buildreq $BUILDREQPARAM "$SPECNAME" $@ || RET=$?
	fi
	return $RET
}

uni_rpminstall()
{
	local RET=0
	local TWOPARAM="-v"

	if [ -n "$RPMTOPDIR" ] ; then
		TWOPARAM="--define=_topdir $RPMTOPDIR"
	fi

	#if is_gear $SPECDIR ; then
	#	$NICE $GEARBUILDREQ --commit -- $@ || RET=$?
	#else
		echo -n "Install package "
		docmd mkdir -p $RPMTOPDIR/SOURCES $RPMTOPDIR/SRPMS $RPMTOPDIR/RPMS
		showcmd rpm -iv "$TWOPARAM" $@
		rpm -iv "$TWOPARAM" $@ || RET=$?
	#fi
	return $RET
}

# remove source and spec
uni_rpmrm()
{
	local TWOPARAM="-v"

	if [ -n "$RPMTOPDIR" ] ; then
		TWOPARAM="--define=_topdir $RPMTOPDIR"
	fi

	showcmd $RPMBUILD "$TWOPARAM" --rmsource --rmspec --nodeps $@
	$RPMBUILD "$TWOPARAM" --rmsource --rmspec --nodeps $@
}

