#!/bin/bash
# 2008 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

ETERBUILDVERSION=162

# Определяем SUDO для использования
SUDO="sudo"
# for some shells? not for bash
test -z "$UID" && UID=`id -u`
if [ $UID = "0" ]; then
	SUDO=""
fi

# Get tmp dir for our using
OURTMPDIR=$TMPDIR
[ -z "$OURTMPDIR" ] || [ -d "$OURTMPDIR" ] || OURTMPDIR=/tmp

# It can be overrides in config
[ -n "$DEFAULTARCH" ] || DEFAULTARCH=i586
[ `uname -m` = "x86_64" ] && DEFAULTARCH=`uname -m`
NICE="nice"
RPMBUILD=rpmbuild

RPMDIR="$HOME/RPM"
# Can be overrided in the scripts
[ -n "$RPMTOPDIR" ] || RPMTOPDIR="$RPMDIR"

[ -n "$APTCONFBASE" ] || APTCONFBASE=$ETERBUILDETC/apt/apt.conf

#OWNERMAIL=`grep "^%packager" ~/.rpmmacros | head -n 1 | sed -e "s/%packager[ \t]*//g"`
OWNERMAIL=`rpm --eval %packager`

UPLOADDIR="$RPMDIR/upload"
LOGDIR="$RPMDIR/log"
REMOTERPMDIR=
HASHERDIR="$HOME/hasher"
HASHER_NOCHECK=nvr,gpg,packager,buildtime
HASHERARG="--eager-cleanup"
[ -n "$DEBUG" ] && HASHERARG="-v $HASHERARG"

RSYNCSISYPHUS=rsync.altlinux.org::ALTLinux/Sisyphus
# obsoleted
RSYNCINCOMING=devel:/incoming
#SSH_KEYFILE=~/.ssh/id_dsa
GIRARHOST=git.alt

BUILDSERVER=
#BUILDSERVERPATH="$HASHERDIR/repo/i586/RPMS.hasher"

PKGREPLBASE=$ETERBUILDDIR/pkgrepl

test -f /etc/eterbuild/config && . /etc/eterbuild/config

if [ -f ~/.config/eterbuild ] ; then
	. ~/.config/eterbuild
elif [ -f ~/.eterbuild-config ] ; then
	. ~/.eterbuild-config
else
	# obsoleted, load if eterbuild-config is missed
	test -f ~/.ebconfig  && . ~/.ebconfig
fi

