#!/bin/bash
# 2008-2010 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

ETERBUILDVERSION=2100

SUDO="sudo"

# for some shells? not for bash
test -z "$UID" && UID=`id -u`
if [ $UID = "0" ]; then
	SUDO=""
fi

# Get tmp dir for our using
OURTMPDIR=$TMPDIR
[ -z "$OURTMPDIR" ] || [ -d "$OURTMPDIR" ] || OURTMPDIR=/tmp

# current arch
SYSARCH=$(uname -m)
uname -m | grep -q "i.86" && SYSARCH=i586

# set default target arch
[ -n "$BUILDARCH" ] || BUILDARCH=$SYSARCH
[ -n "$TARGETARCH" ] || TARGETARCH=$BUILDARCH

NICE="nice"
RPMBUILD=rpmbuild

# CHECKME: works only on ALT?
if which rpm 2>/dev/null >/dev/null ; then
RPMDIR=$(rpm --eval %_topdir) || fatal
[ "$RPMDIR" = "/usr/src/RPM" ] && fatal "Please, set %_topdir in ~/.rpmmacros.
"
RPMTMPDIR=$(rpm --eval %_tmppath) || fatal

# TODO: get from git also?
OWNERMAIL=$(rpm --eval %packager) || fatal
fi

# Can be overrided in the scripts
[ -n "$RPMTOPDIR" ] || RPMTOPDIR="$RPMDIR"

[ -n "$APTCONFBASE" ] || APTCONFBASE=$ETERBUILDETC/apt/apt.conf



NEULOCALE="en_US.utf8"
COMPANYFTP=etersoft.ru
TARGETFTPBASE="/var/ftp"
LOGDIR="$RPMDIR/log"
HASHERBASEDIR="$HOME/hasher"
HASHER_NOCHECK=nvr,gpg,packager,buildtime
HASHERARG=""

# TODO: do not use this notation at all
# for use in help as example branch/distro name
EXAMPLEALTDISTRVERSION="p8"
# FIXME: obsoleted
CURRENTBRANCHNAME="M80"

[ -n "$DEBUG" ] && HASHERARG="-v $HASHERARG"

#SSH_KEYFILE=~/.ssh/id_dsa
# by default will detect gitery, git.alt in ~/.ssh/config
#GIRARHOST=git.alt

# Timeout in sec for ssh commands
SSHTIMEOUT=300

BUILDSERVER=

[ -n "$CCACHE_DIR" ] || CCACHE_DIR=$OURTMPDIR/ccache

# enable ccache using
# CCACHE_ENABLE=yes

# load system wide config
[ -f /etc/eterbuild/config ] && . /etc/eterbuild/config

# load user config files
if [ -f ~/.config/eterbuild ] ; then
	. ~/.config/eterbuild
elif [ -f ~/.eterbuild-config ] ; then
	fatal "./eterbuild-config is obsoleted, use ~/.config/eterbuild instead"
fi

export CCACHE_DIR
