#!/bin/bash
# 2013 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

load_mod repos

# Is allow connect with ssh to the GIRARHOST server?
has_ssh_girar_access()
{
	ssh $GIRARHOST help >/dev/null 2>&1
}

check_http_status()
{
	a= curl -s -I "$1" | grep HTTP | grep -q "200 OK"
}

# Returns true if repo with path from first arg is exits on the remote GIRARHOST server
is_exist_git_repo()
{
	if has_ssh_girar_access ; then
		ssh $GIRARHOST ls $1 >/dev/null 2>&1 && return
	fi
	# TODO: this is workaround for ALT bug #22745
	# https://bugzilla.altlinux.org/show_bug.cgi?id=22745
	check_http_status $(get_git_url $GIRARHOST)/$1
}


# get gear repo for package name
get_girar_repo()
{
	assert_var GIRARHOST
	local PKGNAME="$1"
	# http://git.altlinux.org/gears/N/NAME.git
	local REPOPATH="$(initial_letter $PKGNAME)/$PKGNAME.git"
	local RREPO="/gears/$REPOPATH"
	if ! is_exist_git_repo $RREPO ; then
		RREPO="/srpms/$REPOPATH"
		is_exist_git_repo $RREPO || return
	fi
	echo "$RREPO"
}

