#!/bin/bash
# 2008 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Author: Denis Smirnov <mithraen@altlinux.ru>
# Public domain

get_branch_list()
{
	git branch | grep '^ ' | sed 's/^..\(.*\)/\1/'
}

is_exist_branch()
{
	test -n "$1" || return 1
	get_branch_list | grep $1 >/dev/null
}

get_current_branch()
{
	git branch | grep '^\*' | sed 's/^..//' | tr -d "\n"
}

# Check if $1 like git.alt or git.eter, git.something
is_girar_name()
{
	echo "$1" | grep -q "^git\."
}

_list_git_package()
{
	while [ -n "$1" ] ; do
		printf "%50s  " $GIRARHOST:$1
		shift
		date -d@$1
		shift
	done
}

# TODO: make world better, please
list_git_package()
{
	_list_git_package $(ssh $GIRARHOST find-package $1)
}
