#!/bin/bash
# 2010 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

get_git_url()
{
	grep "^$1 " $ETERBUILDETC/repos/git | cut -f2 -d" "
}

get_rsync_path()
{
	grep "^$1 $2" $ETERBUILDETC/repos/rsync | cut -f3 -d" "
}
