#!/bin/bash
# 2009-2010 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

filter_strip_spaces()
{
        # possible use just
        #xargs echo
        sed -e "s| \+| |g" | \
                sed -e "s|^ ||" | sed -e "s| \$||"
}

strip_spaces()
{
        echo "$*" | filter_strip_spaces
}

# remove_from_list "1." "11 12 21 22" -> "21 22"
remove_from_list()
{
        local i
        local RES=
        for i in $2 ; do
                echo "$i" | grep -q -w "$1" || RES="$RES $i"
        done
        strip_spaces "$RES"
}

# Args: LIST1 LIST2
# do_exclude_list print LIST2 exclude fields contains also in LIST1
# Example: do_exclude_list "1 3" "1 2 3 4" -> "2 4"
do_exclude_list()
{
        local i
        local RES=
        for i in $2 ; do
                echo "$1" | grep -q -w "$i" || RES="$RES $i"
        done
        strip_spaces "$RES"
}

# regexp_exclude_list "22 1." "11 12 21 22" -> "21"
regexp_exclude_list()
{
        local i
        local RES="$2"
        for i in $1 ; do
                RES=$(remove_from_list "$i" "$RES")
        done
        strip_spaces "$RES"
}


# drop listed options
# FIXME: do not handle args like -Uh, only -U -h separately
drop_args()
{
    local ARGS="$1"
    shift
    local LISTIGNORE="$@"
    echo "$ARGS" | sed -e "s|-[${LISTIGNORE/ /}]||g" | sed -e "s| \+| |g" | filter_strip_spaces
    #echo "$ARGS" | \
    #    ( for i in $LISTIGNORE ; do sed -e "s|-$i||g" ;  done ) #| sed -e "s| +| |g"
}

initial_letter()
{
    echo "$1" | head -n1 | cut -c1
}

is_dirpath()
{
    [ "$1" = "." ] && return $?
    echo "$1" | grep -q "/"
}
