#!/bin/bash
# 2009 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

# Use erc universal archivator instead

# DIR FILE
make_md5sum()
{
	cd "$1"
	if [ -n "$2" ] ; then
		rm -f $2.md5
		md5sum -b $2 > $2.md5
	else
		rm -f MD5SUM
		md5sum -b * >MD5SUM
	fi
	cd -
}

