#!/bin/bash
# 2010 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

which xdg-open 2>/dev/null >/dev/null && BROWSER=xdg-open

# (command from perl-libwww)
which GET &>/dev/null && GET=GET || GET=false

download_url()
{
	# use wget with try=1 and timeout = 30 sec
	which wget >/dev/null || fatal "Can't download, wget command is missed"
	a= wget -c -t 1 -T 30 "$1"
}

check_url()
{
	$GET -d "$1"
}
