#!/bin/sh

. /etc/rpm/etersoft-build-functions

#test -n "$SPECNAME" || SPECNAME=$(basename `pwd`).spec

PROJECTNAME=$(basename `pwd`)

git push --all git.alt:packages/$PROJECTNAME.git
git push --tags git.alt:packages/$PROJECTNAME.git

#> $ git commit -a; A='0.23-alt1'; git tag -s $A; \
#>   git tag -s -f -m 'Sisyphus release $A' sisyphus $A