#!/bin/bash
# 2008 Etersoft www.etersoft.ru
# Author: Vitaly Lipatov <lav@etersoft.ru>
# Public domain

. $ETERBUILDDIR/functions/rpm

check_locking()
{
	if [ -f $HASHERDIR/lockdir/lockfile ]
	then
		echo
		echog "Hasher $HASHERDIR in use at `date`"
		echo -n "Wait for unlocking"
		while test -f $HASHERDIR/lockdir/lockfile
		do
			echo -n "."
			sleep $(($RANDOM%5+3))
		done
		echo
	fi
}

# workaround about hard coded path to source.list in apt.conf
print_tmp_aptconf()
{
	test -r "$1" || fatal "$1 is missed"
	# Note: /etc/apt and /etc/eterbuild/apt is supported
	cat "$1" | \
		sed -e "s|\"/etc/.*apt/sources.list|\"$ETERBUILDETC/apt/sources.list|g"
}
